#!/usr/bin/env perl
use FindBin;
use lib ( "$FindBin::RealBin/../lib", "$FindBin::RealBin/../local/lib/perl5" );
use Mojolicious::Lite -signatures;
use Zsearch;
any '/' => sub ($c) {
    my $apikey  = 'becom';
    my $zsearch = Zsearch->new;
    my $origin  = $c->req->headers->origin;
    my $opt     = $c->req->json;
    if ($origin) {
        $c->res->headers->header( 'Access-Control-Allow-Origin' => $origin );
        $c->res->headers->header(
            'Access-Control-Allow-Headers' => 'content-type,X-Requested-With' );
        $c->res->headers->header(
            'Access-Control-Allow-Methods' => 'GET,POST,OPTIONS' );
        $c->res->headers->header(
            'Access-Control-Allow-Credentials' => 'true' );
    }

    # $c->app->log->debug( $c->app->dumper( $c->res->headers ) );
    # Validate
    if ( !$opt->{resource} || !$opt->{method} || !$opt->{apikey} ) {
        my $msg = $zsearch->error->commit(
            "Unknown option specification: resource, method, apikey");
        $c->render( json => $msg );
        return;
    }
    if ( $apikey ne $opt->{apikey} ) {
        my $msg =
          $zsearch->error->commit("apikey is incorrect: $opt->{apikey}");
        $c->render( json => $msg );
        return;
    }

    # Routing
    if ( $opt->{resource} eq 'search' ) {
        my $hash = $zsearch->sql->run($opt);
        $c->app->log->debug( $c->app->dumper($hash) );
        $c->render( json => $hash );
        return;

    }
    my $msg = $zsearch->error->commit("The resource is specified incorrectly");
    $c->render( json => $msg );
    return;
};

app->start;
